name: Deploy to Apps Script üöÄ

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code üõéÔ∏è
        uses: actions/checkout@v3

      - name: Setup Node.js üì¶
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install clasp üõ†Ô∏è
        run: npm install -g @google/clasp

      - name: Create .clasprc.json üîê
        run: |
          echo "$CLASP_TOKEN" > ~/.clasprc.json
        env:
          CLASP_TOKEN: ${{ secrets.CLASP_TOKEN }}

      - name: Push to Apps Script ‚òÅÔ∏è
        run: clasp push -f
